#theme: jekyll-theme-slate
#remote_theme: rundocs/jekyll-rtd-theme
remote_theme: sighingnow/jekyll-gitbook
title: ECHO 
description: Communicaiton tool for analog interplanetary missions

# Specific to this theme
site_author: Dario Schor
repo_url: 'https://github.com/dschor/ECHO '
edit_on_github: true
github_docs_folder: true
logo: 'https://your.url/image.png'
site_favicon: 'https://your.url/here.ico'
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
search_enabled: true
#google_analytics: UA-XXXXX-Y
#google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist

n (i) the challenges while working in a high latency environment with ECHO, 
(ii) what worked in terms of the user interface, 
(iii) improvements and recommendations for the communication tool.